# API calls for TikTok

(disregard, did not work)

docs: https://github.com/davidteather/TikTok-Api & https://davidteather.github.io/TikTok-Api/#

In [1]:
from tiktokapipy.api import TikTokAPI

def do_something():
    with TikTokAPI() as api:
        challenge = api.challenge("climate_change")
        for video in challenge.videos:
            return video_link()

print(do_something)

In [2]:
def test_sort_challenge_videos(sync_api, challenge_name):
    challenge = sync_api.challenge(challenge_name)
    most_recent = -1
    for video in challenge.videos.sorted_by(
        lambda vid: vid.stats.play_count
    ).light_models:
        assert video.stats.play_count >= most_recent
        most_recent = video.stats.play_count

print(test_sort_challenge_videos(, "climate_change"))

<function test_sort_challenge_videos at 0x10a039000>


In [ ]:
from tiktokapipy.api import TikTokAPI

async def scrape_captions_from_challenge(challenge_name):
    async with TikTokAPI() as bot:
        # Search for the challenge
        challenge = await bot.search_challenge(challenge_name)

        # Fetch videos from the challenge
        videos = await bot.get_videos_by_challenge(challenge)

        # Loop through videos and extract captions
        for video in videos:
            video_data = await bot.video(id=video.id)
            subtitles = video_data.subtitle_data
            for subtitle in subtitles:
                print(subtitle.text)

# Example challenge name
challenge_name = 'climate_change'
scrape_captions_from_challenge(challenge_name)


In [ ]:
from TikTokApi import TikTokAPI

api = TikTokAPI()

for video in api.trending.videos():
    print(video.as_dict)

# Simple GET request that relies on CSS selectors

did not work because TikTok relies on javascript to load in the html, therefore without a program like selenium it won't work. API calls above essentially did that, so not work pursuing this method any longer

In [6]:
import requests
from bs4 import BeautifulSoup

# URL of the page to scrape
url = 'https://www.tiktok.com/@davidpakmanshow/video/7221638603321953582'

# Send an HTTP request to the URL
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Use the CSS selector to find the desired content
    # Adjust the selector as per the correct structure of your page
    selector = '#main-content-video_detail > div > div.tiktok-12kupwv-DivContentContainer.ege8lhx2 > div.tiktok-1czmy9n-DivVideoList.ege8lhx5 > div:nth-child(1) > ul'
    element = soup.select_one(selector)

    if element:
        # Process the element as needed, e.g., extract text, links, etc.
        print(element.text)
    else:
        print("Element not found")
else:
    print("Failed to retrieve the webpage")


Element not found


In [5]:
import re

# Sample transcript data
data = "Go green! We gotta make the planet clean. She'll be putting all the right stuff in the recycling bin. Is gonna counteract all of the fumes from the major corporations. Corporations? The fuck the corporations? Corporate. I did it again. All the major corporations. We'll cancel out all of the fumes from the major corporations. Stone cold facts about climate change is that every so often, the earth goes through a massive change completely naturally. Are humans contributing to it? Yes, probably. But not nearly as much as the government is making out. See, over time, the earth gets hotter, and then over time the earth gets colder. That's why we've had several ice ages. And it had absolutely fuck all to do with humans releasing CO2, I can tell you that. The question is, if it is the CO2 that's causing this massive issue, why is it that the little guy who uses almost nothing and still does all the right things for climate change is the one who ends up getting penalised for it? Your government are hoping to rule out things like 15 minutes city so that you can't travel too fast, so that you're not using as much fuel, which bullshit. They've introduced the sugar tax so that our people are more healthy. But then they're the ones that put the sugar in fucking everything. And then also on top of that, it's not gonna do anything apart from put money in the government's pockets. Just When they release the 5 p charge for the plastic bags, did that stop anyone from using plastic bags? No, we just put money in the government's pockets. And they do all this to the little man while completely ignoring the major corporations. I did it again, who are doing all of this. You think about Amazon, Netflix, Google. All these corporations using huge amounts of electricity, all for profit. Majority of them are just dumping it straight back into the ocean when they're done with it. The little guy like you and me who lives in the studio flat and doesn't drive and just only ever uses their fucking phone is apparently the reason why the entire earth is collapsing. And to be perfectly honest, if the overwhelming majority of the population believe all of this shit that's being spewed at us by the World Health Organization, then we deserve to be locked up in 15 minutes cities. Not gonna lie, you too stupid."



# Regular expression to match timestamps
timestamp_pattern = re.compile(r'\d{2}:\d{2}\n?')

# Remove timestamps using regex substitution
cleaned_data = re.sub(timestamp_pattern, '', data)

# Further cleanup if needed (e.g., extra whitespace, special characters)
cleaned_data = cleaned_data.strip().replace('\n', ' ')

print(cleaned_data)


Go green! We gotta make the planet clean. She'll be putting all the right stuff in the recycling bin. Is gonna counteract all of the fumes from the major corporations. Corporations? The fuck the corporations? Corporate. I did it again. All the major corporations. We'll cancel out all of the fumes from the major corporations. Stone cold facts about climate change is that every so often, the earth goes through a massive change completely naturally. Are humans contributing to it? Yes, probably. But not nearly as much as the government is making out. See, over time, the earth gets hotter, and then over time the earth gets colder. That's why we've had several ice ages. And it had absolutely fuck all to do with humans releasing CO2, I can tell you that. The question is, if it is the CO2 that's causing this massive issue, why is it that the little guy who uses almost nothing and still does all the right things for climate change is the one who ends up getting penalised for it? Your government

# New Dataset!!

See info here: https://huggingface.co/datasets/valurank/PoliticalBias_AllSides_Txt

~20k articles labeled left, right, or center by the editors of allsides.com

This function takes the raw data from the allsides.com dataset and looks for references of 'climate change'. If present, it appends the content to a new data set which is either left/right and mentions climate change. 

In [ ]:
import os
import csv


# Function to append file content to CSV
def append_to_csv(file_id, file_path, csv_writer):
    with open(file_path, 'r') as file:
        content = file.read()
        csv_writer.writerow([file_id, os.path.basename(file_path), "left", content])  # 0 is for political_label

# Function to display progress
def display_progress(current, total):
    progress = (current / total) * 100
    print(f'Processing {current}/{total} files ({progress:.2f}%)', end='\r')

# Directory containing the text files
directory = '/Users/bryce/Downloads/AllSides/Left Data'

# Path for the output CSV file
output_csv = 'left_raw_output_w_count.csv'

# List of files in the diectory
files = [f for f in os.listdir(directory) if f.endswith('.txt')]
file_id = 0
# Open the CSV file in write mode
with open(output_csv, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    # Write header
    writer.writerow(['id', 'file_name', 'political_label', 'content'])

    # Process each file
    for i, filename in enumerate(files):
        file_path = os.path.join(directory, filename)

        # Append file content to CSV
        append_to_csv(file_id, file_path, writer)
        file_id += 1
        # Display progress
        display_progress(i + 1, len(files))

print("\nCSV file created:", output_csv)


Processing 7803/7803 files (100.00%)
CSV file created: left_raw_output_w_count.csv


this function normalizes the dataset and combines into 1 dataset

Of important note, because the dataset is filtered for the reference of "climate change" there is an imbalance of entries for left and right...
left = 331
right = 172
This is partially remedied by adjusting the class weights to 'balanced' (this is done in the Word2Vec approach)

In [ ]:
import pandas as pd
import re

def clean_text(text):
    # Normalize unicode characters
    text = text.encode('ascii', 'ignore').decode('ascii')
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+', '', text)
    # Replace newlines and tabs with space
    text = text.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')
    # Remove punctuation and special characters (keep only letters and spaces)
    text = re.sub(r'[^a-zA-Z\s]', '', text, re.I|re.A)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# Load the datasets
left_df = pd.read_csv('left_raw_output_2.csv')
right_df = pd.read_csv('right_raw_output_2.csv')
# center_df = pd.read_csv('center_raw_output_2.csv')  # Uncomment and adjust path as necessary

# Clean the content columns
left_df['cleaned_content'] = left_df['content'].apply(clean_text)
right_df['cleaned_content'] = right_df['content'].apply(clean_text)
# center_df['cleaned_content'] = center_df['content'].apply(clean_text)

# Drop the original 'content' column
left_df = left_df.drop(columns=['content'])
right_df = right_df.drop(columns=['content'])
# center_df = center_df.drop(columns=['content'])  # Uncomment this line if using center_df

# Combine the datasets
combined_df = pd.concat([left_df, right_df], ignore_index=True)  # Add center_df to the list if using

# Save the combined dataset
combined_df.to_csv('combined_dataset_2-labels.csv', index=False)



# Uses Logistic Regression and Tf-IDF (like hmw 3) to predict the odds of being classified as left or right

use 2 labels left and right

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib  # Import joblib for saving and loading models

# Load your dataset
df = pd.read_csv('/Users/bryce/Desktop/INLS697/INLS697_proj/combined_dataset_2-labels.csv')

# Assume 'cleaned_content' is the feature and 'political_label' is the target variable
X = df['cleaned_content']
y = df['political_label']

# Splitting the data into training and valid sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = TfidfVectorizer(ngram_range=(1, 3), max_df=0.85, min_df=3)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_valid_tfidf = vectorizer.transform(X_valid)

# Initialize the Logistic Regression model
model = LogisticRegression(C = 1, class_weight='balanced')

# Train the model
model.fit(X_train_tfidf, y_train)

# Save the trained model and vectorizer
joblib.dump(model, 'models/logistic_regression_model_2_labels.pkl')
joblib.dump(vectorizer, 'models/tfidf_vectorizer_2_labels.pkl')

# Predict on the test set
y_pred = model.predict(X_valid_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_valid, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_valid, y_pred))

# Predict probabilities for the test set
y_pred_proba = model.predict_proba(X_valid_tfidf)
print("Predicted probabilities:\n", y_pred_proba)

Accuracy: 0.7128712871287128

Classification Report:
               precision    recall  f1-score   support

        left       0.72      0.87      0.79        62
       right       0.69      0.46      0.55        39

    accuracy                           0.71       101
   macro avg       0.71      0.67      0.67       101
weighted avg       0.71      0.71      0.70       101

Predicted probabilities:
 [[0.53774126 0.46225874]
 [0.62088276 0.37911724]
 [0.7462755  0.2537245 ]
 [0.54031503 0.45968497]
 [0.45982347 0.54017653]
 [0.58213597 0.41786403]
 [0.56305462 0.43694538]
 [0.6503989  0.3496011 ]
 [0.39920848 0.60079152]
 [0.41866039 0.58133961]
 [0.60093235 0.39906765]
 [0.5849814  0.4150186 ]
 [0.24356741 0.75643259]
 [0.89037341 0.10962659]
 [0.695849   0.304151  ]
 [0.74198712 0.25801288]
 [0.62495953 0.37504047]
 [0.5691392  0.4308608 ]
 [0.54402133 0.45597867]
 [0.59689579 0.40310421]
 [0.58094648 0.41905352]
 [0.50956567 0.49043433]
 [0.57429915 0.42570085]
 [0.53550461 0.464

In [44]:
print(y_test)

173     left
274     left
489    right
72      left
305     left
       ...  
331    right
411    right
502    right
349    right
86      left
Name: political_label, Length: 101, dtype: object


# Multinomial: use 3 labels (left, right and center)

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib  # Import joblib for saving and loading models

# Load your dataset
df = pd.read_csv('/Users/bryce/Desktop/INLS690/final_project/combined_dataset_3-labels.csv')

# Assume 'cleaned_content' is the feature and 'political_label' is the target variable
X = df['cleaned_content']
y = df['political_label']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = TfidfVectorizer(ngram_range=(1, 3), max_df=0.85, min_df=3)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Initialize the Logistic Regression model
model = LogisticRegression(C = 1, multi_class='multinomial')

# Train the model
model.fit(X_train_tfidf, y_train)

# Save the trained model and vectorizer
joblib.dump(model, '/Users/bryce/Desktop/INLS690/final_project/models/logistic_regression_model_3_labels.pkl')
joblib.dump(vectorizer, '/Users/bryce/Desktop/INLS690/final_project/models/tfidf_vectorizer_3_labels.pkl')

# Predict on the test set
y_pred = model.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Predict probabilities for the test set
y_pred_proba = model.predict_proba(X_test_tfidf)
print("Predicted probabilities:\n", y_pred_proba)


Accuracy: 0.625

Classification Report:
               precision    recall  f1-score   support

      center       0.80      0.13      0.23        30
        left       0.62      0.95      0.75        79
       right       0.60      0.22      0.32        27

    accuracy                           0.62       136
   macro avg       0.67      0.43      0.43       136
weighted avg       0.66      0.62      0.55       136

Predicted probabilities:
 [[0.22027071 0.5004158  0.27931349]
 [0.15693906 0.69854433 0.14451661]
 [0.19109065 0.45892087 0.34998848]
 [0.28550768 0.40546214 0.30903017]
 [0.40171729 0.34012487 0.25815783]
 [0.29072206 0.47870174 0.2305762 ]
 [0.34447152 0.39001327 0.26551521]
 [0.25511944 0.50412558 0.24075498]
 [0.33044361 0.34864698 0.32090941]
 [0.20683282 0.2719198  0.52124738]
 [0.28398061 0.33820389 0.37781551]
 [0.21928558 0.38994417 0.39077026]
 [0.23786718 0.39893351 0.36319931]
 [0.30458905 0.4916008  0.20381015]
 [0.31505596 0.33534839 0.34959566]
 [0.27478157

test with single sentence

In [2]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import joblib  # for saving/loading models

# Load the trained model and vectorizer
model = joblib.load('/Users/bryce/Desktop/INLS697/INLS697_proj/models/logistic_regression_model_2_labels.pkl')  # Adjust the filename as necessary
vectorizer = joblib.load('/Users/bryce/Desktop/INLS697/INLS697_proj/models/tfidf_vectorizer_2_labels.pkl')  # Adjust the filename as necessary

# Function to clean the text (should be the same as used during training)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text, re.I|re.A)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# New sentence for testing
new_sentence = "America’s misunderstood border crisis, in 8 charts"
cleaned_sentence = clean_text(new_sentence)

# Vectorize the sentence
vectorized_sentence = vectorizer.transform([cleaned_sentence])

# Predict the class
predicted_class = model.predict(vectorized_sentence)
predicted_proba = model.predict_proba(vectorized_sentence)

class_labels = model.classes_

# Display Predicted Class and Probabilities with Labels
print(f"Analyzed Sentence {new_sentence}")
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:")
for label, proba in zip(class_labels, predicted_proba[0]):
    print(f"{label}: {proba: .4f}")

Analyzed Sentence America’s misunderstood border crisis, in 8 charts
Predicted Class: ['right']
Predicted Probabilities:
left:  0.4121
right:  0.5879


In [75]:


# Load the trained model and vectorizer
model = joblib.load('/Users/bryce/Desktop/INLS690/final_project/models/logistic_regression_model_2_labels.pkl')
vectorizer = joblib.load('/Users/bryce/Desktop/INLS690/final_project/models/tfidf_vectorizer_2_labels.pkl')

# Load the test dataset
test_df = pd.read_csv('/Users/bryce/Desktop/INLS690/Final_project/test.csv')  # Update the path to your test set

# Transform the test set using the loaded vectorizer
X_test_tfidf = vectorizer.transform(test_df['content'])

# Predict on the test set
y_pred_test = model.predict(X_test_tfidf)

# Create a DataFrame with ID and predicted labels
predicted_df = pd.DataFrame({
    'id': test_df['id'],
    'predicted_label': y_pred_test
})

# Save or print the result
print(predicted_df)

# If you want to save to a new CSV file
predicted_df.to_csv('/Users/bryce/Desktop/INLS690/final_project/test_predictions.csv', index=False)


   id predicted_label
0   0           right
1   1           right
2   2           right
3   3           right
4   4           right
5   5           right
6   6           right
7   7           right
8   8           right
9   9           right


# Word2Vec approach

Better approach than TF-IDF because it 

clean up text

In [1]:
import re
import nltk
from nltk.corpus import stopwords

# Download NLTK stop words if not already downloaded
nltk.download('stopwords')

# Get the list of English stop words
stop_words = set(stopwords.words('english'))

def clean_text(text):
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text, re.I|re.A)
    
    # Split the text into words
    words = text.split()
    
    # Remove stop words
    filtered_words = [word for word in words if word not in stop_words]
    
    # Rejoin filtered words back into a string
    text = ' '.join(filtered_words)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()



[nltk_data] Downloading package stopwords to /Users/bryce/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [95]:
import pandas as pd
import gensim
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib
import nltk
from nltk.corpus import stopwords

# Function to tokenize and clean a document
#nltk.download('stopwords')

# Get the list of English stop words
stop_words = set(stopwords.words('english'))

# Updated function to tokenize, clean, and remove stop words
def clean_and_tokenize(sentence):
    words = gensim.utils.simple_preprocess(sentence)
    filtered_words = [word for word in words if word not in stop_words]
    return filtered_words

# Function to create a mean vector for a document based on Word2Vec model
def document_vector(word2vec_model, doc):
    # Remove out-of-vocabulary words
    doc = [word for word in doc if word in word2vec_model.wv.key_to_index]
    return np.mean(word2vec_model.wv[doc], axis=0) if len(doc) > 0 else np.zeros(word2vec_model.vector_size)

# Load dataset
df = pd.read_csv('/Users/bryce/Desktop/INLS690/final_project/combined_dataset_2-labels.csv')

# Split original text and processed text
X_original = df['cleaned_content']  # Original text
X_processed = X_original.apply(clean_and_tokenize)  # Processed text for model input
y = df['political_label']

# Train Word2Vec model
# sg = 1 is Skip-gram; sg = 0 is CBOW (continuous bag of words)
vector_size = 500
window_size = 4
sq_type = 0
word2vec_model = gensim.models.Word2Vec(sentences=X_processed, vector_size=vector_size, window=window_size, min_count=3, workers=4, sg = sq_type)

# Generate document vectors
X_vectors = np.array([document_vector(word2vec_model, doc) for doc in X_processed])

# Split data into training and testing sets
X_train, X_test, X_train_original, X_test_original, y_train, y_test = train_test_split(X_vectors, X_original, y, test_size=0.3, random_state=100)

# Initialize and train Logistic Regression model
logistic_model = LogisticRegression(C=10, max_iter=1000, class_weight='balanced')
logistic_model.fit(X_train, y_train)

# Save models
joblib.dump(logistic_model, '/Users/bryce/Desktop/INLS690/final_project/models/logistic_regression_model_w2v.pkl')
word2vec_model.save('/Users/bryce/Desktop/INLS690/final_project/models/word2vec_model.model')

# Evaluate model
y_pred = logistic_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Function to predict the class and probabilities for a single sentence
def predict_single_sentence(sentence, word2vec_model, logistic_model):
    tokenized_sentence = clean_and_tokenize(sentence)
    sentence_vector = document_vector(word2vec_model, tokenized_sentence).reshape(1, -1)
    predicted_class = logistic_model.predict(sentence_vector)
    predicted_proba = logistic_model.predict_proba(sentence_vector)
    return predicted_class[0], predicted_proba[0]





Accuracy: 0.5657894736842105

Classification Report:
               precision    recall  f1-score   support

        left       0.71      0.52      0.60        96
       right       0.44      0.64      0.52        56

    accuracy                           0.57       152
   macro avg       0.58      0.58      0.56       152
weighted avg       0.61      0.57      0.57       152



# Run Test Set

In [2]:
import pandas as pd
import gensim
import numpy as np
import joblib
from nltk.corpus import stopwords

# Load the trained Word2Vec and Logistic Regression models
logistic_model_saved = joblib.load('/Users/bryce/Desktop/INLS690/final_project/models/logistic_regression_model_w2v.pkl')
word2vec_model_saved = gensim.models.Word2Vec.load('/Users/bryce/Desktop/INLS690/final_project/models/word2vec_model.model')

# Function to clean and tokenize a document (make sure to define the stop_words as before)
def clean_and_tokenize(sentence):
    words = gensim.utils.simple_preprocess(sentence)
    filtered_words = [word for word in words if word not in stop_words]
    return filtered_words

# Function to create a mean vector for a document based on Word2Vec model
def document_vector(word2vec_model_saved, doc):
    doc = [word for word in doc if word in word2vec_model_saved.wv.key_to_index]
    return np.mean(word2vec_model_saved.wv[doc], axis=0) if len(doc) > 0 else np.zeros(word2vec_model_saved.vector_size)

# Load the test dataset
test_df = pd.read_csv('/Users/bryce/Desktop/INLS690/Final_project/large_test_set.csv')  # Update the path to your test set

# Process the test data
X_test_processed = test_df['content'].apply(clean_and_tokenize)

# Generate vectors for the test data
X_test_vectors = np.array([document_vector(word2vec_model_saved, doc) for doc in X_test_processed])

# Predict on the test data
y_pred_test = logistic_model_saved.predict(X_test_vectors)

# Create a DataFrame with ID and predicted labels
predicted_df = pd.DataFrame({
    'id': test_df['id'],
    'predicted_label': y_pred_test
})

# Save or print the result
print(predicted_df)

# Optionally, save to a new CSV file
predicted_df.to_csv('/Users/bryce/Desktop/INLS690/final_project/test_predictions_w2v.csv', index=False)


    id predicted_label
0   10           right
1   11            left
2   12           right
3   13           right
4   14           right
5   15           right
6   16           right
7   17           right
8   18           right
9   19            left
10  20            left
11  21           right
12  22           right
13  23           right
14  24           right
15  25           right
16  26            left
17  27           right
18  28            left
19  29           right
20  30            left
21  31           right
22  32            left


In [22]:
logistic_model_saved = joblib.load('/Users/bryce/Desktop/INLS690/final_project/models/logistic_regression_model_w2v.pkl')

word2vec_model_saved = gensim.models.Word2Vec.load('/Users/bryce/Desktop/INLS690/final_project/models/word2vec_model.model')

def predict_single_sentence_from_saved_model(sentence, word2vec_model_saved, logistic_model_saved):
    tokenized_sentence = clean_and_tokenize(sentence)
    sentence_vector = document_vector(word2vec_model_saved, tokenized_sentence).reshape(1, -1)
    predicted_class = logistic_model_saved.predict(sentence_vector)
    predicted_proba = logistic_model_saved.predict_proba(sentence_vector)
    return predicted_class[0], predicted_proba[0]



# Right Test

In [59]:
test_sentence = " The climate change agenda is a hoax, and we need to declare independence. The reality is the anti-carbon agenda acts as a wet blanket on our economy."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.4170388 0.5829612]


In [32]:
test_sentence = "Withdrew from the unfair, one-sided Paris Climate Agreement."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.3665513 0.6334487]


In [105]:
test_sentence = "It's argued that climate change isn't about saving the earth but about controlling people, and that there's a dislike for the earth and nature at play."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.18128166 0.81871834]


In [104]:
test_sentence = "And when I see these people talking about global warming, where the ocean will rise by a 100th of an inch over the next 350 years, where it's going to get a little bit warmer or a little bit cooler, they don't know. You know, they talk to. We used to be global warming. They don't talk about it as much, though. No, they don't talk? No, they call or went into hiding or something. No, now they call it climate change because they said it's going to get warmer. It was getting colder, then it was going to get colder. It's getting warmer. You know, they used to say global cooling because they thought the world was going to freeze. That was in the 1920s, I think. Global cooling. Then it went to global warming, but that wasn't working, so now they go to climate change because that covers everything. Your real global warming would be nuclear global warming. That's a warming that will take seconds, and that's a warming that will melt granite. You know what granite is? It's a very powerful, very hard stone. If you take a look at Hiroshima, or Hiroshima, as a lot of people call it, Nagasaki, where they used nuclear in a very primitive form, it actually took granite, large areas of granite, and melted it. And now it's like an ice skating rink. It melted into virtual water, and now when it hardened, it was absolutely stone cold level. It melted Granite. You could hit granite with a blowtorch and it won't even do anything to it. So you're talking about a level of power, a level of heat, a level of destruction. Nobody talks about that. They talk about global warming. It's sick. And we have to get rid of nuclear weapons. You know, one of the things I was going to do, and I would have done, is the denouking of everything"
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.09919109 0.90080891]


more christian approach to climate change

In [72]:
test_sentence = "good morning TikTok how are you today I'm pretty good laundry is going in the background I'm getting ready to do another art project here in a minute but first I thought I'd get on here and wrinkle some feathers just by putting a thought out there into the World and this message is for people WHO profess the Faith in Jesus christ and believe in god if you don't feel free to listen but it's not directed at you for those people WHO feel they are Christian and also believe in global climate crisis I'm gonna need you to check back in with god and have a conversation because last I believed god was omnipotent and god created everything this very Earth in fact and the idea that the god WHO created everything was somehow insufficient in his thought process and did not provide an Earth with enough resources for the number of lives he put on it it's mind boggling that you think that he or whatever you want it to be god god just kind of skipped out on that one and therefore you you you and all your other humans will manage the Earth better than the god WHO created it y'all come on get off yourself righteous stuff and start thinking realistically you cannot control the Earth nobody can and you are not smarter than the god WHO created it I'm just saying if you're a Christian and you believe in global climate crisis there's not a checks and balances up there there's not cause it makes no logical sense and that's where i i live in logic there's no logic and it is not Faith based because if you have Faith in god you believe that he provided and it's there for US to take you wanna know who's stopping US other humans and oh by the way last question and this has nothing to do with christianity why do the oil companies get to charge US for the oil they take out of the ground I get that they get to charge US for the processing of it but the oil itself that belongs to all of US we are inheritance of that why do they get to charge US for something that belongs to US start thinking about the Earth as your belonging becaUSe you are an inheritance of what god provided"
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.48832655 0.51167345]


# Left test

In [110]:
test_sentence = "And we have seen, around our country, where communities have been choked by drought, have been washed out by floods, and decimated by hurricanes.  Here in Baltimore, you have seen your skies darkened by wildfire smoke.  And you have seen the waters of the Chesapeake Bay rise, threatening homes and businesses that have stood for generations."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.75684347 0.24315653]


In [111]:
test_sentence = "Hello, my name is Olivia Colwine, and I want to extend a huge thank you on behalf of the fossil fuel industries for your support this year. People like you have invested billions of pounds into our gas and oil businesses. The funds from your pensions have enabled us to dig, drill, and impact the planet more than ever before. We've even constructed some wind turbines to appease environmental activists. Every bit of your investments contributes significantly. As a result, while global temperatures may rise slightly, our profits are significantly increasing, all thanks to your contributions. To ensure a profitable future for us, please continue to direct your pensions our way. You know the drill. Oh, fucking hell. Okay, start skin. Start skin. Yes!"
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.58362119 0.41637881]


In [112]:
test_sentence = "Why is the COP28 climate change summit being used to strike fossil fuel deals? According to BBC-published documents, the United Arab Emirates planned to use the COP28 meetings to promote deals for its national gas and oil companies. The documents suggest discussion points for fossil fuel deals with 15 nations, including China. However, COP28 officials rejected these implications, stating that the president is solely focused on business related to COP and achieving ambitious, transformative climate outcomes. Yet, the emergence of such allegations at a conference like COP28, which can be seen as performative, is not surprising."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.62305211 0.37694789]


In [113]:
test_sentence = "I attended a funeral recently, which was held in a church. It's been a long time since I've been inside a church, but I've noticed that at most church funerals, especially in the South, the pastor often discusses Jesus and the message of Christianity. This particular service had a recurring theme: the world is falling apart and Jesus is the only hope. The interpretation seemed to be that the world is breaking down according to their understanding of scripture, leading to an epiphany for me. It struck me why many Christians might not be concerned about climate change. If the belief is that the world is deteriorating and heading towards an apocalypse, then striving to make the world a better place might seem futile. If anything, this belief could lead to a desire for the world to deteriorate faster, as it would hasten the return of Jesus and the subsequent journey to heaven. This perspective, when analyzed, appears incredibly selfish. It made me think about the societal and civilizational impact of such beliefs and where that places someone on the spectrum of human civilization. It's a thought-provoking realization about the potential implications of certain religious beliefs on environmental concerns. I hope this perspective encourages introspection, especially among Christians, regarding the broader implications of these beliefs."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.58053225 0.41946775]


In [114]:
test_sentence = "Our government has done more to fight climate change than any government in Canadian history. And that is only appropriate. You know, I began my remarks by referring to the forest fires here in Quebec. Uh, yesterday, uh, in Toronto, there was so much smog. Uh, not smogs, so much smoke from the forest fires that Toronto was one of the cities with the poorest air quality in the world. A climate change is upon us. It is a crisis. And the right thing to do is what our government is doing, um, which is to put a price on pollution. We have done that, and we've done that with the price on pollution. We've done that with the clean fuel standards and at the same time to support the innovative Canadian companies, whoever both how important that work in building the clean economy is, um, and that, you know, we, as a country, we can do it. You know, it is very easy to be really, uh, frightened by climate change, and we should be. Um, it is an existential challenge. But I think the response to that needs to be to do what we're doing, which is to invest in Canada and Canadians to have real faith and confidence in people like the brilliant engineers and computer programmers, uh, and innovators who are here. But about the pure regulations, companies shouldn't pass it. One question. 1. What? You say you should pay more? I've given my answer. Thanks. I'm so sorry."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.29294134 0.70705866]


In [116]:
test_sentence = "c"
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.89612507 0.10387493]


# Error analysis

In [ ]:
# Assuming X_test and y_test are your test datasets
predictions = logistic_model.predict(X_test)
probabilities = logistic_model.predict_proba(X_test)

# Create a DataFrame for analysis
error_analysis_df = pd.DataFrame({
    'Text': X_test_original,  # original text of the test set
    'True_Label': y_test,
    'Predicted_Label': predictions,
    'Predicted_Probability': probabilities.max(axis=1)
})
incorrect_predictions = error_analysis_df[error_analysis_df['True_Label'] != error_analysis_df['Predicted_Label']]

print(incorrect_predictions)


# In class example

Video 1

In [102]:
test_sentence = "I attended a funeral recently, which was held in a church. It's been a long time since I've been inside a church, but I've noticed that at most church funerals, especially in the South, the pastor often discusses Jesus and the message of Christianity. This particular service had a recurring theme: the world is falling apart and Jesus is the only hope. The interpretation seemed to be that the world is breaking down according to their understanding of scripture, leading to an epiphany for me. It struck me why many Christians might not be concerned about climate change. If the belief is that the world is deteriorating and heading towards an apocalypse, then striving to make the world a better place might seem futile. If anything, this belief could lead to a desire for the world to deteriorate faster, as it would hasten the return of Jesus and the subsequent journey to heaven. This perspective, when analyzed, appears incredibly selfish. It made me think about the societal and civilizational impact of such beliefs and where that places someone on the spectrum of human civilization. It's a thought-provoking realization about the potential implications of certain religious beliefs on environmental concerns. I hope this perspective encourages introspection, especially among Christians, regarding the broader implications of these beliefs."
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: left
Predicted Probabilities: [0.58053225 0.41946775]


Video 2

In [118]:
test_sentence = "good morning TikTok how are you today I'm pretty good laundry is going in the background I'm getting ready to do another art project here in a minute but first I thought I'd get on here and wrinkle some feathers just by putting a thought out there into the World and this message is for people WHO profess the Faith in Jesus christ and believe in god if you don't feel free to listen but it's not directed at you for those people WHO feel they are Christian and also believe in global climate crisis I'm gonna need you to check back in with god and have a conversation because last I believed god was omnipotent and god created everything this very Earth in fact and the idea that the god WHO created everything was somehow insufficient in his thought process and did not provide an Earth with enough resources for the number of lives he put on it it's mind boggling that you think that he or whatever you want it to be god god just kind of skipped out on that one and therefore you you you and all your other humans will manage the Earth better than the god WHO created it y'all come on get off yourself righteous stuff and start thinking realistically you cannot control the Earth nobody can and you are not smarter than the god WHO created it I'm just saying if you're a Christian and you believe in global climate crisis there's not a checks and balances up there there's not cause it makes no logical sense and that's where i i live in logic there's no logic and it is not Faith based because if you have Faith in god you believe that he provided and it's there for US to take you wanna know who's stopping US other humans and oh by the way last question and this has nothing to do with christianity why do the oil companies get to charge US for the oil they take out of the ground I get that they get to charge US for the processing of it but the oil itself that belongs to all of US we are inheritance of that why do they get to charge US for something that belongs to US start thinking about the Earth as your belonging becaUSe you are an inheritance of what god provided"
cleaned_sentence = clean_text(test_sentence)
predicted_class, predicted_proba = predict_single_sentence_from_saved_model(cleaned_sentence, word2vec_model_saved, logistic_model_saved)
print("Predicted Class:", predicted_class)
print("Predicted Probabilities:", predicted_proba)

Predicted Class: right
Predicted Probabilities: [0.32477443 0.67522557]
